import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bundle } from '@apidevtools/json-schema-ref-parser';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { compile } from 'json-schema-to-typescript';

const packageDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const schemaDirectory = join(packageDirectory, 'schema');
const generatedDirectory = join(packageDirectory, 'src', 'generated');
const schemaNames = [
	'common.schema.json',
	'runtime.schema.json',
	'market-data.schema.json',
	'chart-config.schema.json',
	'indicator.schema.json',
	'pane.schema.json',
	'overlay.schema.json',
	'chart-scene.schema.json',
	'time-series-runtime.schema.json',
	'time-series-chart-config.schema.json',
	'time-series-scene.schema.json',
];

async function readSchemas() {
	return Promise.all(
		schemaNames.map(async (name) => ({
			name,
			schema: JSON.parse(await readFile(join(schemaDirectory, name), 'utf8')),
		})),
	);
}

async function writeIfChanged(path, content) {
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch {
		// 首次生成时目标文件不存在。
	}
	if (current !== content) {
		await writeFile(path, content, 'utf8');
	}
}

function buildSchemaModule(schemas) {
	const entries = schemas.map(({ name, schema }) => {
		const exportName = name
			.replace(/\.schema\.json$/, '')
			.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
			.replace(/^([a-z])/, (_, letter) => letter.toUpperCase());
		return `export const ${exportName}Schema = ${JSON.stringify(schema, null, 2)} as const;`;
	});
	return `/* Generated by scripts/generate.mjs. Do not edit. */\n\n${entries.join('\n\n')}\n`;
}

async function generateTypes() {
	const rootPath = join(schemaDirectory, 'chart-scene.schema.json');
	const bundled = await bundle(rootPath, {
		resolve: {
			baronSchema: {
				order: 1,
				canRead: /^https:\/\/baron\.dev\/kline-scene\/.+\.schema\.json(?:#.*)?$/,
				read(file) {
					const url = new URL(file.url);
					return readFile(join(schemaDirectory, basename(url.pathname)), 'utf8');
				},
			},
		},
	});
	bundled.properties.metadata = { tsType: 'JsonObject' };
	const generated = await compile(bundled, 'ChartScene', {
		additionalProperties: false,
		bannerComment: '/* Generated by scripts/generate.mjs. Do not edit. */',
		cwd: schemaDirectory,
		declareExternallyReferenced: true,
		format: true,
		maxItems: -1,
		strictIndexSignatures: true,
		unknownAny: true,
		style: {
			bracketSpacing: true,
			printWidth: 100,
			semi: true,
			singleQuote: true,
			tabWidth: 2,
			trailingComma: 'all',
			useTabs: true,
		},
	});
	return `${generated}\nexport type JsonPrimitive = null | boolean | number | string;\nexport type JsonValue = JsonPrimitive | JsonValue[] | JsonObject;\nexport interface JsonObject {\n\t[key: string]: JsonValue | undefined;\n}\n`;
}

async function generateTimeSeriesTypes() {
	const rootPath = join(schemaDirectory, 'time-series-scene.schema.json');
	const bundled = await bundle(rootPath, {
		resolve: {
			baronSchema: {
				order: 1,
				canRead: /^https:\/\/baron\.dev\/kline-scene\/.+\.schema\.json(?:#.*)?$/,
				read(file) {
					const url = new URL(file.url);
					return readFile(join(schemaDirectory, basename(url.pathname)), 'utf8');
				},
			},
		},
	});
	bundled.properties.metadata = { tsType: 'TimeSeriesMetadata' };
	const generated = await compile(bundled, 'TimeSeriesScene', {
		additionalProperties: false,
		bannerComment: '/* Generated by scripts/generate.mjs. Do not edit. */',
		cwd: schemaDirectory,
		declareExternallyReferenced: true,
		format: true,
		maxItems: -1,
		strictIndexSignatures: true,
		unknownAny: true,
		style: {
			bracketSpacing: true,
			printWidth: 100,
			semi: true,
			singleQuote: true,
			tabWidth: 2,
			trailingComma: 'all',
			useTabs: true,
		},
	});
	return `${generated}\nexport type TimeSeriesMetadataValue = null | boolean | number | string;\nexport interface TimeSeriesMetadata {\n\t[key: string]: TimeSeriesMetadataValue | undefined;\n}\n`;
}

function generateValidator(schemas, rootId, exportName) {
	const ajv = new Ajv2020({
		allErrors: true,
		code: {
			esm: true,
			source: true,
		},
		strict: true,
	});
	for (const { schema } of schemas) {
		ajv.addSchema(schema);
	}
	ajv.getSchema(rootId);
	const standalone = standaloneCode(ajv, { [exportName]: rootId }).replace(
		/const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/,
		`const $1 = (value) => { let length = 0; for (const _character of value) length++; return length; };`,
	);
	if (standalone.includes('require("ajv/')) {
		throw new Error('Generated validator still depends on the Ajv runtime.');
	}
	return `// @ts-nocheck -- generated standalone validator\n${standalone}\n`;
}

const schemas = await readSchemas();
await mkdir(generatedDirectory, { recursive: true });
await writeIfChanged(join(generatedDirectory, 'schemas.ts'), buildSchemaModule(schemas));
await writeIfChanged(join(generatedDirectory, 'chart-scene.ts'), await generateTypes());
await writeIfChanged(
	join(generatedDirectory, 'time-series-scene.ts'),
	await generateTimeSeriesTypes(),
);
await writeIfChanged(
	join(generatedDirectory, 'validate-chart-scene.ts'),
	generateValidator(
		schemas,
		'https://baron.dev/kline-scene/chart-scene.schema.json',
		'validateChartScene',
	),
);
await writeIfChanged(
	join(generatedDirectory, 'validate-time-series-scene.ts'),
	generateValidator(
		schemas,
		'https://baron.dev/kline-scene/time-series-scene.schema.json',
		'validateTimeSeriesScene',
	),
);
