import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bundle } from '@apidevtools/json-schema-ref-parser';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { compile } from 'json-schema-to-typescript';

const packageDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const schemaDirectory = join(packageDirectory, 'schema');
const generatedDirectory = join(packageDirectory, 'src', 'generated');
const schemaNames = [
	'common.schema.json',
	'runtime.schema.json',
	'market-data.schema.json',
	'chart-config.schema.json',
	'indicator.schema.json',
	'pane.schema.json',
	'overlay.schema.json',
	'chart-scene.schema.json',
	'drawing-document.schema.json',
	'drawable-workspace.schema.json',
	'time-series-runtime.schema.json',
	'time-series-chart-config.schema.json',
	'time-series-scene.schema.json',
];

const PERIOD_REF = 'https://baron.dev/kline-scene/common.schema.json#/$defs/period';

async function readSchemas() {
	return Promise.all(
		schemaNames.map(async (name) => ({
			name,
			schema: JSON.parse(await readFile(join(schemaDirectory, name), 'utf8')),
		})),
	);
}

async function writeIfChanged(path, content) {
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch {
		// 首次生成时目标文件不存在。
	}
	if (current !== content) {
		await writeFile(path, content, 'utf8');
	}
}

async function readSchemaJson(name) {
	return JSON.parse(await readFile(join(schemaDirectory, name), 'utf8'));
}

/** 把根 Schema 中指向公共 period 的引用重定向到本根 $defs，以固定公共类型名。 */
function redirectPeriodRefs(node, targetName) {
	if (Array.isArray(node)) {
		for (const child of node) {
			redirectPeriodRefs(child, targetName);
		}
		return;
	}
	if (node !== null && typeof node === 'object') {
		for (const [key, value] of Object.entries(node)) {
			if (key === '$ref' && value === PERIOD_REF) {
				node.$ref = `#/$defs/${targetName}`;
			} else {
				redirectPeriodRefs(value, targetName);
			}
		}
	}
}

async function loadRootWithLocalPeriod(name, periodDefName) {
	const root = await readSchemaJson(name);
	const common = await readSchemaJson('common.schema.json');
	redirectPeriodRefs(root, periodDefName);
	root.$defs = root.$defs ?? {};
	root.$defs[periodDefName] = common.$defs.period;
	return root;
}

async function bundleRoot(schemaObject) {
	return bundle(schemaObject, {
		resolve: {
			baronSchema: {
				order: 1,
				canRead: /^https:\/\/baron\.dev\/kline-scene\/.+\.schema\.json(?:#.*)?$/,
				read(file) {
					const url = new URL(file.url);
					return readFile(join(schemaDirectory, basename(url.pathname)), 'utf8');
				},
			},
		},
	});
}

const compileOptions = {
	additionalProperties: false,
	bannerComment: '/* Generated by scripts/generate.mjs. Do not edit. */',
	cwd: schemaDirectory,
	declareExternallyReferenced: true,
	format: true,
	maxItems: -1,
	strictIndexSignatures: true,
	unknownAny: true,
	style: {
		bracketSpacing: true,
		printWidth: 100,
		semi: true,
		singleQuote: true,
		tabWidth: 2,
		trailingComma: 'all',
		useTabs: true,
	},
};

function buildSchemaModule(schemas) {
	const entries = schemas.map(({ name, schema }) => {
		const exportName = name
			.replace(/\.schema\.json$/, '')
			.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase())
			.replace(/^([a-z])/, (_, letter) => letter.toUpperCase());
		return `export const ${exportName}Schema = ${JSON.stringify(schema, null, 2)} as const;`;
	});
	return `/* Generated by scripts/generate.mjs. Do not edit. */\n\n${entries.join('\n\n')}\n`;
}

async function generateChartTypes() {
	const root = await loadRootWithLocalPeriod('chart-scene.schema.json', 'period');
	const bundled = await bundleRoot(root);
	bundled.properties.metadata = { tsType: 'JsonObject' };
	const generated = await compile(bundled, 'ChartScene', compileOptions);
	return `${generated}\nexport type JsonPrimitive = null | boolean | number | string;\nexport type JsonValue = JsonPrimitive | JsonValue[] | JsonObject;\nexport interface JsonObject {\n\t[key: string]: JsonValue | undefined;\n}\n`;
}

async function generateTimeSeriesTypes() {
	const root = await loadRootWithLocalPeriod('time-series-scene.schema.json', 'timeSeriesPeriod');
	const bundled = await bundleRoot(root);
	bundled.properties.metadata = { tsType: 'TimeSeriesMetadata' };
	const generated = await compile(bundled, 'TimeSeriesScene', compileOptions);
	return `${generated}\nexport type TimeSeriesMetadataValue = null | boolean | number | string;\nexport interface TimeSeriesMetadata {\n\t[key: string]: TimeSeriesMetadataValue | undefined;\n}\n`;
}

async function generateDrawingTypes() {
	const root = await loadRootWithLocalPeriod('drawing-document.schema.json', 'drawingPeriod');
	const bundled = await bundleRoot(root);
	bundled.properties.metadata = { tsType: 'DrawingMetadata' };
	const generated = await compile(bundled, 'DrawingDocument', compileOptions);
	return `${generated}\nexport type DrawingMetadataValue = null | boolean | number | string;\nexport interface DrawingMetadata {\n\t[key: string]: DrawingMetadataValue | undefined;\n}\n`;
}

async function generateWorkspaceTypes() {
	const root = await loadRootWithLocalPeriod(
		'drawable-workspace.schema.json',
		'drawingPeriod',
	);
	const bundled = await bundleRoot(root);
	bundled.properties.metadata = { tsType: 'DrawableWorkspaceMetadata' };
	const generated = await compile(bundled, 'DrawableWorkspaceDocument', compileOptions);
	return `${generated}\nexport type DrawableWorkspaceMetadataValue = null | boolean | number | string;\nexport interface DrawableWorkspaceMetadata {\n\t[key: string]: DrawableWorkspaceMetadataValue | undefined;\n}\n`;
}

function generateValidator(schemas, rootId, exportName) {
	const ajv = new Ajv2020({
		allErrors: true,
		code: {
			esm: true,
			source: true,
		},
		strict: true,
	});
	for (const { schema } of schemas) {
		ajv.addSchema(schema);
	}
	ajv.getSchema(rootId);
	const standalone = standaloneCode(ajv, { [exportName]: rootId }).replace(
		/const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/,
		`const $1 = (value) => { let length = 0; for (const _character of value) length++; return length; };`,
	);
	if (standalone.includes('require("ajv/')) {
		throw new Error('Generated validator still depends on the Ajv runtime.');
	}
	return `// @ts-nocheck -- generated standalone validator\n${standalone}\n`;
}

const schemas = await readSchemas();
await mkdir(generatedDirectory, { recursive: true });
await writeIfChanged(join(generatedDirectory, 'schemas.ts'), buildSchemaModule(schemas));
await writeIfChanged(join(generatedDirectory, 'chart-scene.ts'), await generateChartTypes());
await writeIfChanged(
	join(generatedDirectory, 'time-series-scene.ts'),
	await generateTimeSeriesTypes(),
);
await writeIfChanged(
	join(generatedDirectory, 'drawing-document.ts'),
	await generateDrawingTypes(),
);
await writeIfChanged(
	join(generatedDirectory, 'drawable-workspace.ts'),
	await generateWorkspaceTypes(),
);
await writeIfChanged(
	join(generatedDirectory, 'validate-chart-scene.ts'),
	generateValidator(
		schemas,
		'https://baron.dev/kline-scene/chart-scene.schema.json',
		'validateChartScene',
	),
);
await writeIfChanged(
	join(generatedDirectory, 'validate-time-series-scene.ts'),
	generateValidator(
		schemas,
		'https://baron.dev/kline-scene/time-series-scene.schema.json',
		'validateTimeSeriesScene',
	),
);
await writeIfChanged(
	join(generatedDirectory, 'validate-drawing-document.ts'),
	generateValidator(
		schemas,
		'https://baron.dev/kline-scene/drawing-document.schema.json',
		'validateDrawingDocument',
	),
);
await writeIfChanged(
	join(generatedDirectory, 'validate-drawable-workspace.ts'),
	generateValidator(
		schemas,
		'https://baron.dev/kline-scene/drawable-workspace.schema.json',
		'validateDrawableWorkspace',
	),
);
