import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'vite';

const packageDirectory = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const outputDirectory = await mkdtemp(join(tmpdir(), 'baron-render-runtime-'));
const placeholder = '__BARON_SCENE_BASE64__';

function singleMatch(source, expression, label) {
	const matches = source.match(expression) ?? [];
	if (matches.length !== 1) {
		throw new Error(`Expected exactly one ${label}; found ${matches.length}.`);
	}
}

function assertSelfContained(html) {
	singleMatch(html, new RegExp(placeholder, 'g'), 'Scene Base64 placeholder');
	if (/<(?:script|link|img|source|video|audio)\b[^>]*(?:src|href)=["'](?!data:|#)/iu.test(html)) {
		throw new Error('Standalone HTML contains an external executable or fetchable asset.');
	}
	if (/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource)\s*\(/u.test(html)) {
		throw new Error('Standalone Runtime contains a network API call.');
	}
	if (/\bimport\s*\(/u.test(html)) {
		throw new Error('Standalone Runtime contains a dynamic module import.');
	}
	if (/@font-face[^}]*url\((?!["']?data:)/isu.test(html)) {
		throw new Error('Standalone Runtime contains an external font URL.');
	}
}

try {
	await build({
		root: packageDirectory,
		logLevel: 'warn',
		build: {
			assetsInlineLimit: Number.MAX_SAFE_INTEGER,
			cssCodeSplit: false,
			emptyOutDir: true,
			minify: 'esbuild',
			modulePreload: false,
			outDir: outputDirectory,
			rollupOptions: {
				input: join(packageDirectory, 'browser', 'index.html'),
				output: {
					inlineDynamicImports: true,
					entryFileNames: 'runtime.js',
					assetFileNames: 'runtime[extname]',
				},
			},
		},
	});
	let html = await readFile(join(outputDirectory, 'browser', 'index.html'), 'utf8');
	const javascript = (await readFile(join(outputDirectory, 'runtime.js'), 'utf8'))
		.replace(/<\/script/giu, '<\\/script');
	const css = (await readFile(join(outputDirectory, 'runtime.css'), 'utf8'))
		.replaceAll('"Noto Sans SC Variable"', '"Baron Sans"')
		.replaceAll("'Noto Sans SC Variable'", "'Baron Sans'");
	Function(javascript);
	html = html
		.replace(
			/<script type="module"[^>]*src="[^"]*"[^>]*><\/script>/u,
			() => `<script type="module">${javascript}</script>`,
		)
		.replace(
			/<link rel="stylesheet"[^>]*href="[^"]*"[^>]*>/u,
			() => `<style>${css}</style>`,
		);
	assertSelfContained(html);
	const hash = createHash('sha256').update(html).digest('hex');
	const generatedDirectory = join(packageDirectory, 'generated');
	await mkdir(generatedDirectory, { recursive: true });
	await writeFile(join(generatedDirectory, 'runtime-template.html'), html, 'utf8');
	const generated = [
		'/* Generated by scripts/build-runtime.mjs. Do not edit. */',
		'',
		`export const SCENE_BASE64_PLACEHOLDER = ${JSON.stringify(placeholder)};`,
		`export const STANDALONE_HTML_SHA256 = ${JSON.stringify(hash)};`,
		`export const STANDALONE_HTML_TEMPLATE = ${JSON.stringify(html)};`,
		'',
	].join('\n');
	await writeFile(join(packageDirectory, 'src', 'assets.generated.ts'), generated, 'utf8');
} finally {
	await rm(outputDirectory, { recursive: true, force: true });
}
